load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_shared_library.bzl", "cc_shared_library")
load("//python:py_library.bzl", "py_library")
load("//tests/support:copy_file.bzl", "copy_file_to_dir")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "increment_impl",
    srcs = ["increment.c"],
    deps = [":increment_headers"],
)

cc_library(
    name = "increment_headers",
    hdrs = ["increment.h"],
)

cc_shared_library(
    name = "increment",
    user_link_flags = select({
        "@platforms//os:osx": [
            # Needed so that DT_NEEDED=libincrement.dylib can find
            # this shared library
            "-Wl,-install_name,@rpath/libincrement.dylib",
        ],
        "//conditions:default": [],
    }),
    deps = [":increment_impl"],
)

cc_library(
    name = "adder_impl",
    srcs = ["adder.c"],
    deps = [
        ":increment_headers",
        "@rules_python//python/cc:current_py_cc_headers",
    ],
)

cc_shared_library(
    name = "adder",
    # Necessary for several reasons:
    # 1. Ensures the output doesn't include increment itself (avoids ODRs)
    # 2. Adds -lincrement (DT_NEEDED for libincrement.so)
    # 3. Ensures libincrement.so is available at link time to satisfy (2)
    dynamic_deps = [":increment"],
    # Part 1 To make this test fail:
    # we need to name this to start with `lib` so that 
    # _is_linker_loaded_library() returns true.
    shared_lib_name = "libadder.so",
    tags = ["manual"],
    # NOTE: cc_shared_library adds Bazelized rpath entries, too.
    user_link_flags = [
    ] + select({
        "@platforms//os:osx": [
            "-Wl,-rpath,@loader_path/libs",
            "-undefined",
            "dynamic_lookup",
            "-Wl,-exported_symbol",
            "-Wl,_PyInit_adder",
        ],
        # Assume linux default
        "//conditions:default": [
            "-Wl,-rpath,$ORIGIN/libs",
        ],
    }),
    deps = [":adder_impl"],
)

copy_file_to_dir(
    name = "relocate_adder",
    src = ":adder",
    # Part 2 To make this test fail:
    # Move adder to same folder as increment so group size > 2
    out_dir = "site-packages/ext_with_libs/libs",
    tags = ["manual"],
)

copy_file_to_dir(
    name = "relocate_increment",
    src = ":increment",
    out_dir = "site-packages/ext_with_libs/libs",
    tags = ["manual"],
)

py_library(
    name = "ext_headers",
    # Part 3 Separate the header to another lib to emulate what happens
    # with nvidia. We get a giant group with prefix ext_with_lib, instead
    # of various small groups.
    srcs = ["site-packages/ext_with_libs/__init__.py"],
    experimental_venvs_site_packages = "//python/config_settings:venvs_site_packages",
    imports = [package_name() + "/site-packages"],
    tags = ["manual"],
)

py_library(
    name = "ext_with_libs",
    deps = [":ext_headers"],
    # Revert to this and see .so s appear!
    # srcs = ["site-packages/ext_with_libs/__init__.py"],
    data = [
        ":relocate_adder",
        ":relocate_increment",
    ],
    experimental_venvs_site_packages = "//python/config_settings:venvs_site_packages",
    imports = [package_name() + "/site-packages"],
    tags = ["manual"],
)


# Run bazel build tests/venv_site_packages_libs:shared_lib_loading_test
# Observe adder and increment are missing
# ```
# ls bazel-bin/tests/venv_site_packages_libs/shared_lib_loading_test.runfiles/_main/tests/venv_site_packages_libs/_shared_lib_loading_test.venv/lib/python3.11/site-packages/ext_with_libs/
# __init__.py
# ```
# Simply just revert change 3, and observe they appear!
